---
- name: "End play if distribution not suported"
  meta: end_host
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: "Check for 3cx_exporter binary"
  stat:
    path: "{{ cx_exporter_install_dir }}/3cx-exporter"
  changed_when: false
  register: cx_exporter_install

- when: not cx_exporter_install.stat.exists or cx_exporter_force_install|bool
  block:
    - name: "Download 3cx_exporter..."
      get_url:
        url: '{{ cx_exporter_url }}'
        dest: '{{ cx_exporter_install_dir }}/3cx-exporter'
        timeout: '60'
        mode: '0755'

    - name: "Create config directory"
      file:
        path: '/etc/3cx_exporter'
        state: directory
        mode: '0755'

- name: "Create config file for  3cx_exporter"
  template:
    src: 'config.json.j2'
    dest: '/etc/3cx_exporter/config.json'
    mode: '0644'
  notify: "restart 3cx_exporter"

- name: "Create systemd for 3cx_exporter"
  template:
    src: '3cx_exporter.service.j2'
    dest: '/etc/systemd/system/3cx_exporter.service'
    mode: '0644'
  notify: "restart 3cx_exporter"

- name: "Enable and Start 3cx_exporter.service"
  systemd:
    name: 3cx_exporter
    state: started
    enabled: true
    daemon_reload: true
