---
- name: "Check for 3cx_exporter binary"
  stat:
    path: "/usr/local/bin/3cx_exporter"
  changed_when: false
  register: cx_exporter_install

- when: not cx_exporter_install.stat.exists
  block:
    - name: "Download 3cx_exporter..."
      get_url:
        url: '{{ cx_exporter_url }}'
        dest: '/usr/local/bin/'
        timeout: '120'
        mode: '0755'

    - name: "Create config directory"
      file:
        path: '/etc/3cx_exporter'
        state: directory
        mode: '0755'

- name: "Create config file for  3cx_exporter"
  template:
    src: 'config.json.j2'
    dest: '/etc/3cx_exporter/config.json'
    mode: '0644'
  notify: "restart 3cx_exporter"

- name: "Create systemd for 3cx_exporter"
  template:
    src: '3cx_exporter.service.j2'
    dest: '/etc/systemd/system/cx_exporter.service'
    mode: '0644'
  notify: "restart 3cx_exporter"

- name: "Enable and Start cx_exporter.service"
  systemd:
    name: cx_exporter
    state: started
    enabled: true
    daemon_reload: true
